website/views.py
from flask import Blueprint, render_template, request, flash, jsonify, redirect, url_for
from flask_login import login_required, current_user

from website.role import role_required
from .models import *
from . import db
import json


views = Blueprint("views", __name__)


@views.route("/")
def homepage():
    print("session")
    menu_items = MonAn.query.all()
    return render_template("user/homepage.html", menu=menu_items,user = current_user)



@views.route("/admin-home")
@role_required(["Nhân viên kho", "Quản lý", "Nhân viên"])
def admin_home():
    print(current_user)
    return render_template("admin/admin-home.html")

website/templates/user/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- 
    - primary meta tags
  -->
    <title>
      {% block title %}Grilli - Amazing & Delicious Food{% endblock %}
    </title>
    <meta name="title" content="Grilli - Amazing & Delicious Food" />
    <meta
      name="description"
      content="This is a Restaurant html template made by codewithsadee"
    />

    <!-- 
    - favicon
  -->
    <link
      rel="shortcut icon"
      href="{{url_for('static',filename='images/favicon.svg')}}"
      type="image/svg+xml"
    />

    <!-- 
    - google font link
  -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;700&family=Forum&display=swap"
      rel="stylesheet"
    />

    <!-- 
    - custom css link
  -->
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/styleofhomepage.css') }}"
    />

    <!-- 
    - preload images
  -->
    <link
      rel="preload"
      as="image"
      href="{{ url_for('static', filename='images/hero-slider-1.jpg') }}"
    />
    <link
      rel="preload"
      as="image"
      href="{{ url_for('static', filename='images/hero-slider-2.jpg') }}"
    />
    <link
      rel="preload"
      as="image"
      href="{{ url_for('static', filename='images/hero-slider-3.jpg') }}"
    />
  </head>

  <body id="top">
    <!-- 
    - #PRELOADER
  -->

    <div class="preload" data-preaload>
      <div class="circle"></div>
      <p class="text">Grilli</p>
    </div>

    <!-- 
    - #TOP BAR
  -->

    <div class="topbar">
      <div class="container">
        <address class="topbar-item">
          <div class="icon">
            <ion-icon name="location-outline" aria-hidden="true"></ion-icon>
          </div>

          <span class="span">
            Restaurant St, Delicious City, London 9578, UK
          </span>
        </address>

        <div class="separator"></div>

        <div class="topbar-item item-2">
          <div class="icon">
            <ion-icon name="time-outline" aria-hidden="true"></ion-icon>
          </div>

          <span class="span">Daily : 8.00 am to 10.00 pm</span>
        </div>

        <a href="tel:+11234567890" class="topbar-item link">
          <div class="icon">
            <ion-icon name="call-outline" aria-hidden="true"></ion-icon>
          </div>

          <span class="span">+1 123 456 7890</span>
        </a>

        <div class="separator"></div>

        <a href="mailto:booking@restaurant.com" class="topbar-item link">
          <div class="icon">
            <ion-icon name="mail-outline" aria-hidden="true"></ion-icon>
          </div>

          <span class="span">booking@restaurant.com</span>
        </a>
      </div>
    </div>

    <!-- 
    - #HEADER
  -->

    <header class="header" data-header>
      <div class="container">
        <a href="#" class="logo">
          <img
            src="{{url_for('static',filename='images/logo.svg')}}"
            width="160"
            height="50"
            alt="Grilli - Home"
          />
        </a>

        <nav class="navbar" data-navbar>
          <button class="close-btn" aria-label="close menu" data-nav-toggler>
            <ion-icon name="close-outline" aria-hidden="true"></ion-icon>
          </button>

          <a href="#" class="logo">
            <img
              src="{{url_for('static',filename='images/logo.svg')}}"
              width="160"
              height="50"
              alt="Grilli - Home"
            />
          </a>

          <ul class="navbar-list">
            <li class="navbar-item">
              <a href="#home" class="navbar-link hover-underline active">
                <div class="separator"></div>

                <span class="span">Home</span>
              </a>
            </li>

            <li class="navbar-item">
              <a href="#menu" class="navbar-link hover-underline">
                <div class="separator"></div>

                <span class="span">Menus</span>
              </a>
            </li>

            <li class="navbar-item">
              <a href="#about" class="navbar-link hover-underline">
                <div class="separator"></div>

                <span class="span">About Us</span>
              </a>
            </li>

            <li class="navbar-item">
              <a href="#" class="navbar-link hover-underline">
                <div class="separator"></div>

                <span class="span">Our Chefs</span>
              </a>
            </li>

            <li class="navbar-item">
              <a href="#" class="navbar-link hover-underline">
                <div class="separator"></div>

                <span class="span">Contact</span>
              </a>
            </li>
            <li class="navbar-item">
  {% if current_user.is_authenticated %}  <!-- Kiểm tra xem người dùng đã đăng nhập chưa -->
    <a href="{{ url_for('nguoidung.account') }}" class="navbar-link hover-underline">
      <div class="separator"></div>
      <span class="span">Information</span>
    </a>
  {% else %}
    <a href="{{ url_for('auth.login') }}" class="navbar-link hover-underline">
      <div class="separator"></div>
      <span class="span">Login</span>
    </a>
  {% endif %}
</li>

            
          </ul>

          <div class="text-center">
            <p class="headline-1 navbar-title">Visit Us</p>

            <address class="body-4">
              Restaurant St, Delicious City, <br />
              London 9578, UK
            </address>

            <p class="body-4 navbar-text">Open: 9.30 am - 2.30pm</p>

            <a href="mailto:booking@grilli.com" class="body-4 sidebar-link"
              >booking@grilli.com</a
            >

            <div class="separator"></div>

            <p class="contact-label">Booking Request</p>

            <a
              href="tel:+88123123456"
              class="body-1 contact-number hover-underline"
            >
              +88-123-123456
            </a>
          </div>
        </nav>

        <a href="{{url_for("bookcalendar.index")}}" class="btn btn-secondary">
          <span class="text text-1">Booking</span>

          <span class="text text-2" aria-hidden="true">Booking </span>
        </a>

        <button class="nav-open-btn" aria-label="open menu" data-nav-toggler>
          <span class="line line-1"></span>
          <span class="line line-2"></span>
          <span class="line line-3"></span>
        </button>

        <div class="overlay" data-nav-toggler data-overlay></div>
      </div>
    </header>

    <main>
      

      <article>
        {% block content %}
        <!-- 
        - #HERO
      -->

        {% endblock %}
      </article>
    </main>

    <!-- 
    - #FOOTER
  -->

    <footer
      class="footer section has-bg-image text-center"
      style="background-image: url('./static/images/footer-bg.jpg')"
    >
      <div class="container">
        <div class="footer-top grid-list">
          <div class="footer-brand has-before has-after">
            <a href="#" class="logo">
              <img
                src="{{url_for('static',filename='images/logo.svg')}}"
                width="160"
                height="50"
                loading="lazy"
                alt="grilli home"
              />
            </a>

            <address class="body-4">
              Restaurant St, Delicious City, London 9578, UK
            </address>

            <a href="mailto:booking@grilli.com" class="body-4 contact-link"
              >booking@grilli.com</a
            >

            <a href="tel:+88123123456" class="body-4 contact-link"
              >Booking Request : +88-123-123456</a
            >

            <p class="body-4">Open : 09:00 am - 01:00 pm</p>

            <div class="wrapper">
              <div class="separator"></div>
              <div class="separator"></div>
              <div class="separator"></div>
            </div>

            <p class="title-1">Get News & Offers</p>

            <p class="label-1">
              Subscribe us & Get <span class="span">25% Off.</span>
            </p>

            <form action="" class="input-wrapper">
              <div class="icon-wrapper">
                <ion-icon name="mail-outline" aria-hidden="true"></ion-icon>

                <input
                  type="email"
                  name="email_address"
                  placeholder="Your email"
                  autocomplete="off"
                  class="input-field"
                />
              </div>

              <button type="submit" class="btn btn-secondary">
                <span class="text text-1">Subscribe</span>

                <span class="text text-2" aria-hidden="true">Subscribe</span>
              </button>
            </form>
          </div>

          <ul class="footer-list">
            <li>
              <a href="#" class="label-2 footer-link hover-underline">Home</a>
            </li>

            <li>
              <a href="#" class="label-2 footer-link hover-underline">Menus</a>
            </li>

            <li>
              <a href="#" class="label-2 footer-link hover-underline"
                >About Us</a
              >
            </li>

            <li>
              <a href="#" class="label-2 footer-link hover-underline"
                >Our Chefs</a
              >
            </li>

            <li>
              <a href="#" class="label-2 footer-link hover-underline"
                >Contact</a
              >
            </li>
          </ul>

          <ul class="footer-list">
            <li>
              <a href="#" class="label-2 footer-link hover-underline"
                >Facebook</a
              >
            </li>

            <li>
              <a href="#" class="label-2 footer-link hover-underline"
                >Instagram</a
              >
            </li>

            <li>
              <a href="#" class="label-2 footer-link hover-underline"
                >Twitter</a
              >
            </li>

            <li>
              <a href="#" class="label-2 footer-link hover-underline"
                >Youtube</a
              >
            </li>

            <li>
              <a href="#" class="label-2 footer-link hover-underline"
                >Google Map</a
              >
            </li>
          </ul>
        </div>

        <div class="footer-bottom">
          <p class="copyright">
            &copy; 2022 Grilli. All Rights Reserved | Crafted by
            <a
              href="https://github.com/codewithsadee"
              target="_blank"
              class="link"
              >codewithsadee</a
            >
          </p>
        </div>
      </div>
    </footer>

    <!-- 
    - #BACK TO TOP
  -->

    <a
      href="#top"
      class="back-top-btn active"
      aria-label="back to top"
      data-back-top-btn
    >
      <ion-icon name="chevron-up" aria-hidden="true"></ion-icon>
    </a>

    <!-- 
    - custom js link
  -->
    {% block javascript %}
    <script src="{{url_for('static',filename='js/script.js')}}"></script>

    <!-- 
    - ionicon link
  -->
    <script
      type="module"
      src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"
    ></script>
    <script
      nomodule
      src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"
    ></script>
    
    {% endblock %}
  </body>
</html>

website/templates/user/book.html
<!DOCTYPE html>
<html lang="vi">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Lịch Tương Tác</title>
  <!-- FullCalendar CSS -->
  <link href="https://cdn.jsdelivr.net/npm/fullcalendar@5.11.3/main.min.css" rel="stylesheet" />
  <!-- jQuery -->
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <!-- FullCalendar JS -->
  <script src="https://cdn.jsdelivr.net/npm/fullcalendar@5.11.3/main.min.js"></script>
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    body {
      font-family: "Roboto", sans-serif;
      background-color: #f8f9fa;
      margin: 0;
      padding: 0;
      display: flex;
      flex-direction: column;
      align-items: center;
    }

    h1 {
      text-align: center;
      color: #343a40;
      margin-bottom: 20px;
    }

    #container {
      display: flex;
      justify-content: space-between;
      width: 100%;
      max-width: 1200px;
      margin-top: 20px;
      flex-wrap: nowrap;
    }

    #calendar {
      flex: 2 1 65%;
      margin-right: 20px;
      background: white;
      border-radius: 8px;
      box-shadow: 0 4px 15px rgba(0, 0, 0, 0.1);
    }

    #event-form {
      flex: 1 1 30%;
      background-color: white;
      padding: 20px;
      border-radius: 8px;
      box-shadow: 0 4px 15px rgba(0, 0, 0, 0.1);
    }

    #event-form h3 {
      text-align: center;
      color: #007bff;
      margin-bottom: 20px;
    }

    #event-form input,
    #event-form select,
    #event-form textarea {
      width: 100%;
      padding: 10px;
      margin: 10px 0;
      border-radius: 8px;
      border: 1px solid #ddd;
      background-color: #f8f9fa;
      font-size: 16px;
    }

    #event-form input:focus,
    #event-form select:focus,
    #event-form textarea:focus {
      border-color: #007bff;
      outline: none;
    }

    #event-form button {
      background-color: #28a745;
      color: white;
      border: none;
      padding: 12px;
      border-radius: 8px;
      cursor: pointer;
      font-size: 16px;
      width: 100%;
      transition: background-color 0.3s ease;
    }

    #event-form button:hover {
      background-color: #218838;
    }

    #success-message {
      color: #28a745;
      margin-top: 15px;
      text-align: center;
      font-size: 16px;
      display: none;
    }

    /* Responsive Design */
    @media (max-width: 768px) {
      #container {
        flex-direction: column;
        align-items: center;
      }

      #calendar {
        width: 100%;
        margin-bottom: 20px;
      }

      #event-form {
        width: 100%;
        margin-top: 20px;
      }
    }
  </style>
</head>

<body>
  <!-- <h1>Đặt lịch</h1> -->
  <div id="container">
    <!-- Calendar -->
    <div id="calendar"></div>

    <!-- Event Form -->
    <div id="event-form">
      <h3>Đặt Lịch Hẹn</h3>
      <label for="event-name">Họ và tên:</label>
      <input type="text" id="event-name" placeholder="Họ và tên" name="event-name"
        value="{{ khachhang.HoKH +" " +khachhang.TenKH}}" required />
      <label for="event-sdt">SDT
        <p class="note">(Nếu có thay đổi vui lòng đổi ở thông tin cá nhân):</p>
      </label>
      <input type="tel" id="event-phone" placeholder="Số điện thoại" name="event-phone" value="{{khachhang.SDT}}"
        required />
      <label for="event-email">Email
        <p class="note">(Nếu có thay đổi vui lòng đổi ở thông tin cá nhân):</p>
      </label>
      <input type="email" id="event-email" placeholder="Email" name="event-email" value="{{khachhang.Email}}"
        required />
      <div>
        <label for="event-date">Ngày đặt <span style="color: red;">*</span></label>
        <input type="date" id="event-date" name="event-date" required />
      </div>
      <div>
        <label for="event-arrival-time">Giờ đến <span style="color: red;">*</span></label>
        <input type="time" id="event-arrival-time" name="event-arrival-time" required />
      </div>
      <div>
        <label for="event-duration">Khoảng thời gian (phút)<span style="color: red;">*</span></label>
        <input type="number" id="event-duration" placeholder="Khoảng thời gian (phút)" min="1" name="event-duration"
          required />
      </div>
      <label for="event-soluongnguoi">Số lượng người <span style="color: red;">*</span></label>
      <input type="number" id="soluongnguoi" placeholder="Số lượng người" name="soluongnguoi" required min="1" />

      <div class="d-flex justify-content-between mt-4" style="display: flex;flex-direction: row;gap: 10px;">
        <button id="save-event" type="submit">Lưu sự kiện</button>
        <button>
          <a href="{{url_for('views.homepage')}}" class="btn btn-secondary "
            style="Text-decoration: none;color: white;">Quay lại</a>
        </button>

      </div>
      <div id="success-message">Sự kiện đã được lưu thành công!</div>
    </div>
  </div>
  <script>
    document.addEventListener("DOMContentLoaded", function () {
      const calendarEl = document.getElementById("calendar");

      // Khởi tạo lịch với các tùy chỉnh
      const calendar = new FullCalendar.Calendar(calendarEl, {
        initialView: "timeGridWeek",
        headerToolbar: {
          left: "prev,next today",
          center: "title",
          right: "timeGridWeek,timeGridDay",
        },
        editable: false,
        selectable: true,
        allDaySlot: false,
        slotDuration: "00:05:00",
        displayEventTime: true,
        slotMinTime: "08:00:00",
        slotMaxTime: "22:00:00",

        // Fetch events for calendar
        events: function (info, successCallback, failureCallback) {
          $.ajax({
            url: "/bookcalendar/get_unavailable_times",
            method: "GET",
            success: function (response) {
              if (response.status === "success") {
                const events = response.data.map(event => ({
                  start: event.start_time,
                  end: event.end_time,
                  title: "Đã đặt lịch",
                  rendering: "background",
                  color: "red",
                }));
                successCallback(events);
              } else {
                failureCallback("Không tải được dữ liệu lịch");
              }
            },
            error: function () {
              failureCallback("Lỗi kết nối đến server");
            },
          });
        },

        // Xử lý sự kiện khi chọn trên lịch
        select: function (info) {
          const start = info.start;
          const end = info.end;
          console.log("start", start)
          const date = start.toISOString().split("T")[0];
          console.log("date", date)
          const hours = start.getHours().toString().padStart(2, "0");

          const minutes = start.getMinutes().toString().padStart(2, "0");
          const duration = (end - start) / (1000 * 60);
          console.log("duration", duration)
          document.getElementById("event-date").value = date;
          document.getElementById("event-arrival-time").value = `${hours}:${minutes}`;
          document.getElementById("event-duration").value = duration;
        },
      });

      calendar.render();

      // Xử lý lưu sự kiện
      document.getElementById("save-event").addEventListener("click", function (e) {
        e.preventDefault();

        // Lấy giá trị từ form
        const name = document.getElementById("event-name").value.trim();
        const phone = document.getElementById("event-phone").value.trim();
        const email = document.getElementById("event-email").value.trim();
        const date = document.getElementById("event-date").value;
        const time = document.getElementById("event-arrival-time").value;
        const duration = parseInt(document.getElementById("event-duration").value, 10);
        const number_persons = parseInt(document.getElementById("soluongnguoi").value, 10);
        console.log("time", time)
        // Kiểm tra hợp lệ của form
        if (!name || !phone || !email || !date || !time || isNaN(duration) || isNaN(number_persons)) {
          showMessage("Vui lòng điền đầy đủ thông tin!", "error");
          return;
        }
        console.log("phone", phone)
        if (phone == "None") {
          showMessage("Bạn cần cập nhật số điện thoại ở trang cá nhân!", "error");
          return;
        }
        if (!/^\d{10}$/.test(phone)) {
          showMessage("Số điện thoại không hợp lệ!", "error");
          return;
        }

        if (!/^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$/.test(email)) {
          showMessage("Email không hợp lệ!", "error");
          return;
        }
        if (duration < 30) {
          showMessage("Thời lượng cần lớn hơn 30 phút!", "error");
          return;
        }
        // Kiểm tra ngày đặt phải lớn hơn ngày giờ hiện tại
        const now = new Date(); // Lấy ngày giờ hiện tại
        const bookingDate = new Date(NgayDat); // Chuyển đổi NgayDat thành đối tượng Date

        if (bookingDate <= now) {
          showMessage("Ngày đặt phải lớn hơn ngày giờ hiện tại!", "error");
          return;
        }


        // Tính toán thời gian bắt đầu và kết thúc
        const start = new Date(`${date}T${time}`);
        const end = new Date(start.getTime() + duration * 60 * 1000);

        // Gửi dữ liệu đến server
        $.ajax({
          url: "/bookcalendar/save_event",
          method: "POST",
          contentType: "application/json",
          data: JSON.stringify({
            name: name,
            phone: phone,
            email: email,
            date: date,
            time: time,
            duration: duration,
            number_persons: number_persons,
          }),
          success: function (response) {
            if (response.status === "success") {
              showMessage("Sự kiện đã được lưu thành công!", "success");
              calendar.refetchEvents();
              resetForm();
            } else {
              showMessage("Đã xảy ra lỗi khi lưu sự kiện!", "error");
            }
          },
          error: function () {
            showMessage("Không thể kết nối đến server.", "error");
          },
        });
      });

      // Hàm hiển thị thông báo
      function showMessage(message, type) {
        const successMessage = document.getElementById("success-message");
        successMessage.textContent = message;
        successMessage.style.color = type === "success" ? "green" : "red";
        successMessage.style.display = "block";

        setTimeout(() => {
          successMessage.style.display = "none";
        }, 5000); // Tăng thời gian để người dùng đọc thông báo
      }

      // Hàm đặt lại form
      function resetForm() {
        document.getElementById("event-name").value = "";
        document.getElementById("event-phone").value = "";
        document.getElementById("event-email").value = "";
        document.getElementById("event-date").value = "";
        document.getElementById("event-arrival-time").value = "";
        document.getElementById("event-duration").value = "";
        document.getElementById("soluongnguoi").value = "";
      }
    });
  </script>
  <style>
    .note {
      background-color: #fef8e4;
      padding: 10px;
      border-left: 4px solid #f0ad4e;
      margin-top: 10px;
      font-size: 13px;
    }
  </style>
</body>

</html>